return {
	MaxCombo = 4,
	ComboResetTime = 2.0,
	ComboFinishPause = 0.5,

	MinSwingIntervalFloor = 0.065,
	HitboxActiveTime = 0.08,
	HitboxFallbackDelay = 0.1,
	StateReleasePadding = 0.04,

	AttackTrackFadeTime = 0.04,
	AttackTrackPriority = Enum.AnimationPriority.Action2,
	AttackWalkSpeed = 6,
	RestoreWalkSpeed = 9,
	EnableCombatSfx = true,
	EnableWeaponTrails = true,
	UseBodyTrailFallback = false,
	FallbackBodyTrailDuration = 0.2,
	FallbackBodyTrailLocation = "BodyTrail1",
	VfxReplicationRadius = 180,
	RunningTriggerMinSpeed = 11,
	RunningTriggerHintMinSpeed = 11,
	RunningTriggerMinMove = 0.2,

	BaseKnockback = 8,
	FinalKnockback = 30,
	BaseStun = 0.45,
	FinalStun = 1.8,
	FinalHitRagdoll = false,
	FinalHitRagdollDuration = 0,
	DefaultMaxPosture = 100,
	BlockPosturePerDamage = 4,
	PerfectParrySelfPostureRecover = 5,
	PerfectParryEnemyPostureDamage = 10,
	ParryAttackerStun = 0.5,
	ParryDefenderStun = 0.3,
	AutoParryWindow = 0,
	AutoParryMaxHits = 12,
	AutoParryMaxHitGap = 0.4,
	AutoParrySelfPostureGain = 5,
	AutoParryAttackerStun = 0.2,
	GuardBreakStun = 2,

	CombatTagDuration = 45,
}
